version: '2'

services:
  todoList_api:
    build: .
    image: to_do_list:latest
    container_name: to_do_list
    restart: always
    environment:
      MYSQL_DSN: "root:root@/to_do_list?charset=utf8&parseTime=True&loc=Local"
    ports:
      - 3002:3000
    depends_on:
      - redis
      - mysql
    networks:
      - hello

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "to_do_list"
    volumes:
      - conf/config.ini: /etc/conf/config.ini
    ports:
      - "3306:3306"
    networks:
      - hello

  redis:
    container_name: redis
    image: redis:5.0.10
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hello


networks:
  hello:
    external:
      true